name: Update Timestamp and create Tag

on:
  push:
    branches:
      - development

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for changes in version
        id: check_version
        run: |
          # Get the latest commit hash and check if version changed
          git fetch origin development
          if git show --name-only --pretty=format: | grep -q "version"; then
            echo "version has changed."
            echo "changed=true" >> $GITHUB_ENV
          else
            echo "version has not changed."
            echo "changed=false" >> $GITHUB_ENV
          fi

      - name: Update timestamp and create tag
        if: env.changed == 'true'  # Only run if version has changed
        run: |
          # Read the current version and increment it
          current_version=$(cat version)

          # Output the Unix timestamp to timeStamp
          date -u +%s > timeStamp

          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add timeStamp
          git commit -m "Update timestamp of version $current_version"

      - name: Push changes to main
        if: env.changed == 'true'  # Only run if version has changed
        run: |
          git push

      - name: Create new tag
        if: env.changed == 'true'  # Only run if version has changed
        run: |
          # Create a new tag based on the updated version
          git tag $(cat version) # Ensure the tag format is correct
          git push origin $(cat version) # Push the new tag to the remote